spring.application.name=emergency-alert-api

# * การต่อกับ Database
spring.config.import=classpath:database.properties, classpath:jwt.properties, classpath:imageKit.properties

# * Spring Config
spring.main.banner-mode=off
logging.level.root=warn
server.port=8080